services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: lawpy-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/import
      - mongodb_data:/data/db
    networks:
      - lawpy-network
    restart: unless-stopped

  django:
    build:
      context: ./LawPy
      dockerfile: Dockerfile
    container_name: lawpy-django
    ports:
      - "8000:8000"
    volumes:
      - ./LawPy:/app
    depends_on:
      - mongodb
    networks:
      - lawpy-network
    environment:
      - MONGODB_HOST=mongodb
    env_file:
      - ./.env
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./LawPy/frontend
      dockerfile: Dockerfile
    container_name: lawpy-frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    depends_on:
      - django
    networks:
      - lawpy-network
    restart: unless-stopped

networks:
  lawpy-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 